### PR TITLE
Add a note about persistent notification behavior starting in Android 14

### PR DESCRIPTION
**Pull request by dshokouhi**
We have a upcoming behavior change to one of our parameters so need to inform the user about this.

Ref: https://github.com/home-assistant/android/issues/3655

Actual docs: https://developer.android.com/about/versions/14/behavior-changes-all#non-dismissable-notifications

### CODE REVIEW

**Comment by jpelgrom** [comment]
Should the box be placed after the first paragraph perhaps, to allow users to understand what a persistent notification is first before detailing version-specific behavior? For example see the device compatiblity box after 'Notification Message HTML Formatting'.

> the user / user

Use 'you' like the main text.

> will be dismissable

Right now Android 14 is the future, but not once it is released; use 'can be dismissed'.

> the phone

More generic: the device.

**Comment by dshokouhi** [comment]
thanks for the suggestion, applied the recommendations :)

**Comment by jpelgrom** [comment]
You left a new blank line (367) ;)

**Review by jpelgrom — APPROVED** [review]

**Comment by harmpter** [comment]
I'm very exited I found a solution via ADB
```
adb shell appops set --uid io.homeassistant.companion.android SYSTEM_EXEMPT_FROM_DISMISSIBLE_NOTIFICATIONS allow
```

I wonder whether it is appropriate to have the docs hint at this possibility. 
If yes, I would love to finally dip my toes into contributing to HA (the docs at least, lets start off cool right?)

**Comment by mrdarrengriffin** [comment]
Oh that's really slick @harmpter

**Comment by dshokouhi** [comment]
> I wonder whether it is appropriate to have the docs hint at this possibility.

forums would be a better place for unofficial fixes like this

**Comment by jpelgrom** [comment]
> > I wonder whether it is appropriate to have the docs hint at this possibility.
> 
> forums would be a better place for unofficial fixes like this

Adding to that: including information like this in the documentation suggests (a certain level of) support for it by the HA developers, which is hard to provide for an internal flag in Android that may not work on every device or stop working.

**Pull request merged**
