### PR TITLE
Notification: "when_relative" for "chronometer"

### PR DESCRIPTION
**Pull request by Roffild**
https://github.com/home-assistant/android/pull/4273

### CODE REVIEW

**Comment by jpelgrom** [comment]
Can you add a beta label, to indicate this is not yet available? See any other documentation PR describing a new feature as an example.

**Comment by dshokouhi** [comment]
> > Can you add a beta label, to indicate this is not yet available? See any other documentation PR describing a new feature as an example.
> 
> I do not have rights to add labels.

thats not what was asked, please look at a previous PR to add a beta label like this one https://github.com/home-assistant/companion.home-assistant/pull/1036

**Review by dshokouhi — CHANGES_REQUESTED** [review]
please add a beta label next to the newly introduced parameter

**Comment by Roffild** [comment]
This is not beta. This is the final feature :)

**Review by jpelgrom — APPROVED** [review]

**Pull request merged**
