### PR TITLE
Change app configuration references

### PR DESCRIPTION
**Pull request by ludeeus**
For https://github.com/home-assistant/frontend/pull/10733

### CODE REVIEW

**Comment by TomBrien** [comment]
Agreed there'll also be some changes when the multi server docs merge

**Comment by TomBrien** [comment]
Just realised I posted on parent not here earlier 🤦‍♂️

**Comment by dshokouhi** [comment]
Do you think we need to mention it was moved in 2021.12? I do see the occasional user who can't find app configuration in its current location

**Review by TomBrien — COMMENTED** [review]
#After this change was merged to core-dev last night, I think we need to reword slightly further as the entry isn't labelled "Companion App Configuration". Perhaps "Companion App section of Configuration"? And better yet we should include a my link to configuration
image

**Comment by ludeeus** [comment]
I'll update this next week

**Comment by TomBrien** [comment]
@ludeeus can we knock this out soon? I'm happy to do the last changes if you're short on time

**Comment by ludeeus** [comment]
Sorry, forgot about this.
If you have time, please do 🙏 if not I'll see if I can find time tomorrow or Monday

**Review by dshokouhi — APPROVED** [review]

**Comment by ludeeus** [comment]
Thanks @TomBrien :+1:

**Pull request merged**
