### PR TITLE
Add documentation for sending a broadcast intent

### PR DESCRIPTION
**Pull request by dshokouhi**
Docs for: https://github.com/home-assistant/android/pull/1129

Also provided a real world example from a popular app to show how it works.

### CODE REVIEW

**Comment by dshokouhi** [comment]
Merging as the parent PR is merged and want to make sure users see the format.

**Comment by frenck** [comment]
@dshokouhi You should not merge your own PRs. At least do a shoutout on Discord for help.

**Comment by dshokouhi** [comment]
@frenck apologies, I normally am the only one submitting updates for Android and at times we move pretty fast with PR's and our beta users are used to seeing the docs updated around the same time the PR is merged since they get notified.  I will make sure to do a shoutout in Discord next time.  This is just the pattern I am used to when we are adding features since the docs have a tendency to fall behind.

**Comment by TomBrien** [comment]
I should apologise for @dshokouhi here. I think we have a habit of just trusting each other on iOS and Android. Bit of a hangover from when I was the only one doing stuff on this. I tend to see these I'll try and remember to make sure I approve when I see there's no issues.

**Comment by frenck** [comment]
> apologies, I normally am the only one submitting updates for Android and at times we move pretty fast with PR's and our beta users are used to seeing the docs updated around the same time the PR is merged since they get notified.

Parent PRs should not be merged without docs either.

**Comment by TomBrien** [comment]
Let's get the templates updated on the code repos. @frenck can we leverage the bot code from core and main docs repo?

**Pull request merged**
