### PR TITLE
Update docs to reflect new gif functionality

### PR DESCRIPTION
**Pull request by NickM-27**
References https://github.com/home-assistant/android/pull/4284 which adds support for showing animated gifs in notifications on Android 14+

### CODE REVIEW

**Comment by dshokouhi** [comment]
We should also mention its only available in the beta :)

**Comment by NickM-27** [comment]
is there a process setup for updating those docs once the beta is upgraded to prod release? Mostly just curious

**Comment by dshokouhi** [comment]
> is there a process setup for updating those docs once the beta is upgraded to prod release? Mostly just curious

yea one of us members will either create a PR removing them as we submit to prod or we just prepare a PR after Google approves the prod push. We always merge only after its been released to try and keep things as up to date as possible.

**Review by dshokouhi — APPROVED** [review]
Looks good to me can be merged when parent is merged

**Pull request merged**
