### PR TITLE
Bump Docusaurus to alpha50

### PR DESCRIPTION
**Pull request by TomBrien**
This repo isn't getting caught by dependabot

### CODE REVIEW

**Comment by frenck** [comment]
@TomBrien It is caught by dependabot, however, it can take up to 24 hours (unless you beat him to it 😉 )

**Comment by TomBrien** [comment]
@frenck it was 10 versions behind and the other two Docusaurus V2 repos have been updating nicely. Dependabot seems to miss docusaurus on this one. The other dependencies seem to get updated

**Comment by frenck** [comment]
I see now! Darn, will check the config

**Comment by TomBrien** [comment]
Cheers, I had a quick look (apparently the app just takes write permissions for access btw...) but couldn't see any clear difference. Do let me know if you find something

**Comment by frenck** [comment]
I've removed and re-added dependabot for this repository, maybe that helps 🤷‍♂

**Pull request merged**
