### PR TITLE
Initial commit of android flavors

### PR DESCRIPTION
**Pull request by dshokouhi**
The android app is now offered as both a `full` or `minimal` version so this will highlight the differences between them.  While we are at it lets also mention how users can help test out unreleased features/fixes with the `debug` builds.

### CODE REVIEW

**Comment by dshokouhi** [comment]
CC: @jbassett I think I captured the differences correctly right?

**Comment by dshokouhi** [comment]
Should we add a new column to the comparison table for the `minimal` flavor to really show what they can/can't do?

**Comment by JBassett** [comment]
You captured the differences.  Adding a table might be nice.  Hopefully we can bring the two in line so they offer the same feature set eventually.

**Comment by dshokouhi** [comment]
@JBassett So its only battery and wifi connection sensor the `minimal` flavor gets for now right? Geocoded is obviously a play services one lol.

**Comment by JBassett** [comment]
@dshokouhi that's correct

**Comment by dshokouhi** [comment]
ok cool, will update and add to the table :) thanks for confirming!

**Comment by dshokouhi** [comment]
@TomBrien when you get a moment can you see if the table looks alright with the new column? Not sure if there is any room for improvement there :)

**Comment by TomBrien** [comment]
Looks fine in terms of screen width to me. We should probably `vertical-align: top` the `th` cells is all.

**Comment by dshokouhi** [comment]
@TomBrien better now? For some reason I don't see a difference on my end lol

**Comment by TomBrien** [comment]
> @TomBrien better now? For some reason I don't see a difference on my end lol

For record needed to be done like <td style="vertical-align: top;>` but it's tidier to just stick a class on the table and add the CSS rules

**Pull request merged**
