### PR TITLE
Update attachments.md

### PR DESCRIPTION
**Pull request by Malnes**
just, why?!

### CODE REVIEW

**Comment by TomBrien** [comment]
Can you please supply some context/background for this. The intended behaviour is that the app handles the authentication of the media folder as described [here](https://www.home-assistant.io/integrations/media_source/) and [here](https://companion.home-assistant.io/docs/notifications/notification-attachments#media_source-recommended)

If this is the case, a bug report should be raised, not a change to the docs.

**Comment by Malnes** [comment]
I don’t see anything in the documentation explaining why files stored in /media suddenly becomes publicly available, but after much testing, that is the case.

First, I created a snapshot:

service: camera.snapshot
data:
  filename: /media/testImg.jpg
target:
  entity_id: camera.cam3_sd_stream



At this stage, the following url Returns 401, which is good.
https://<domain>.com/media/local/testImg.jpg
Then i added the image to a Notification:



service: notify.mobile_app_malnes_mobil
data:
  message: Test message
  title: Test message
  data:
    image: /media/local/testImg.jpg
    actions:
      - action: URI
        title: Open
        uri: https://<domain>.com/media/local/testImg.jpg<https://%3cdomain%3e.com/media/local/testImg.jpg>




After sending the Notification, the image is available for the world to see.
Don’t know if it’s a bug or a feature, you tell me.

Also, the image is available even after deleting the image from /media folder (getting some Eufy vibes here). Tried deleting and disabling cache from cloudflare, but that did not help either. It’s my understanding that HA use google notification services (firebase?) to deliver notifications, and I assume this is just a limitiation with that service.
OR this is just me doing something wrong…..



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by zacwest** [comment]
Sounds like you have allowed Cloudflare to cache it somehow. I recommend looking there first; accessing HA directly will not allow access to the file without authentication. It makes sense that after validly pulling it your caching proxy could cache it.

**Comment by Malnes** [comment]
I have disabled and deleted cache in cloudflare. I don’t think that’s the issue, but I will investigate further.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Pull request closed without merging**
