### PR TITLE
Allow fan domain in android auto

### PR DESCRIPTION
**Pull request by cwrogers**

### CODE REVIEW

**Comment by cwrogers** [comment]
Docs for: https://github.com/home-assistant/android/pull/4757

**Comment by dshokouhi** [comment]
Thanks for the PR and docs! As this will first be part of a beta release once merged please add the beta tag so users may know its only available in the beta version of the app. You may refer to a previous PR for the correct format to use.

**Comment by dshokouhi** [comment]
Thanks for the update :) feel free to mark this as ready for review if you are happy with it

**Review by dshokouhi — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
