### PR TITLE
Update Actions docs to include new 'use_custom_colors'

### PR DESCRIPTION
**Pull request by bgoncal**

### CODE REVIEW

**Comment by bgoncal** [comment]
Waiting to merge when App version is available on App Store

**Comment by bgoncal** [comment]
iOS PR: https://github.com/home-assistant/iOS/pull/2880
Core PR: https://github.com/home-assistant/core/pull/122767

**Comment by biscuitee** [comment]
Need help . 

How do I opt in and enable the custom color in IOS Watch?  I couldn't find the documentation on this configuration

**Comment by bgoncal** [comment]
> Need help .
> 
> How do I opt in and enable the custom color in IOS Watch? I couldn't find the documentation on this configuration

It will come on App version 2024.8, if you want it now, download the beta via testflight, otherwise wait until next week.
About the documentation, you are commenting on the PR thats adds it :)

**Comment by rhyswaywood** [comment]
Can this documentation be merged now that app version 2024.8 has been shipped?

**Comment by bgoncal** [comment]
> Can this documentation be merged now that app version 2024.8 has been shipped?

Thanks for the reminder

**Pull request merged**
