### PR TITLE
Fix an example with actionable notification url

### PR DESCRIPTION
**Pull request by denysdovhan**
I've spent too much time trying to figure out what I'm doing wrong here. Turns out it was a typo in an example. I hope this will save someone's time.

### CODE REVIEW

**Comment by dshokouhi** [comment]
Do we need to worry about the second example just beneath as well? I don't use iOS so not sure about the expected format here.

**Review by TomBrien — CHANGES_REQUESTED** [review]
@denysdovhan sorry for taking ages to get to this and thanks for fixing.

Can you update the next example https://github.com/home-assistant/companion.home-assistant/blob/3de4a5c6e24c2808356a9a232f5e099d6cb14a23/docs/notifications/actionable.md#L125-L136
to add the missing `data` key after `message`  

We should mention this won't work with actions which have `activationMode: background` (@zacwest can we workaround that if there is an URL defined for an action)

**Review by TomBrien — APPROVED** [review]
Looks great now. Thanks for sorting this 👍

**Comment by denysdovhan** [comment]
Thank you!

**Pull request merged**
