### PR TITLE
Switch from Oculus to Meta for the docs

### PR DESCRIPTION
**Pull request by dshokouhi**
Now that the official mobile apps have been updated I guess its time to update our docs 😄

### CODE REVIEW

**Review by TomBrien — COMMENTED** [review]
Do we want some redirects to handle people hitting to old oculus docs from direct links?

**Comment by dshokouhi** [comment]
Oh right ya I guess we should add the redirect. Good call

**Comment by dshokouhi** [comment]
@TomBrien did I get the redirect link correct here?

**Review by TomBrien — APPROVED** [review]
Yikes, sorry completely missed those. All good I think

**Pull request merged**
