### PR TITLE
Add docs for updating ble transmitter measured power

### PR DESCRIPTION
**Pull request by dshokouhi**
Docs for: https://github.com/home-assistant/android/pull/4546

### CODE REVIEW

**Comment by jpelgrom** [comment]
This section is getting a lot of examples, I'm wondering if perhaps adding things to a list/table like above would be better. Did you consider this?

**Comment by dshokouhi** [comment]
> This section is getting a lot of examples, I'm wondering if perhaps adding things to a list/table like above would be better. Did you consider this?

yea a table does not make much sense here because we can only update 1 item at a time, only measured power can be updated and a separate command needs to be sent to turn off teh transmitter or adjust the advertise mode etc...

**Comment by jpelgrom** [comment]
I suppose that is true. Let's save the discussion about the number of examples in the documentation for another time ;)

**Review by jpelgrom — APPROVED** [review]
Good to merge when Android PR is merged

**Pull request merged**
