### PR TITLE
add info about multiple media players to media player widget docs

### PR DESCRIPTION
**Pull request by jannis3005**
This corresponds to PR [2534](https://github.com/home-assistant/android/pull/2534) in the homeassistant android repository.

### CODE REVIEW

**Review by dshokouhi — CHANGES_REQUESTED** [review]
Sorry for the late review, this one fell off the radar. This feature is actually first available in the beta version of the android app. Would you be able to update this PR to split things up so users are aware the new features are only available in the beta with a beta tag? Once we cut a release we will remove the tags.

**Comment by jannis3005** [comment]
I wasn't quiet sure on where/how to put them. is this as you intended @dshokouhi ?

**Comment by jpelgrom** [comment]
The stable version of the app has actually been updated earlier this week so the beta tag is no longer necessary 🙂

**Comment by dshokouhi** [comment]
My bad forgot to respond here and mention that :(

**Comment by dshokouhi** [comment]
@jannis3005 any chance you can update this one more time? We don't need to mention beta anymore as this change is already in the production version.

**Review by dshokouhi — APPROVED** [review]

**Pull request merged**
