### PR TITLE
Update meta-quest.md

### PR DESCRIPTION
**Pull request by tctctctc**
Add Meta Quest Pro and Meta Quest 3 to a list of supported devices.

### CODE REVIEW

**Comment by dshokouhi** [comment]
do you have both devices? App logs in and launches fine and no issues with sensors and other features?

**Comment by tctctctc** [comment]
Yes. I have both and have been testing companion app for several month. Everything works like it works on quest 2. I used them in everyday automation, and test them with iBeacon integration. I didn't find any different from quest 2.

**Review by dshokouhi — APPROVED** [review]
Thank you for confirming the app works on these devices!

**Comment by tctctctc** [comment]
App starts in background and log in automaticly  as it should and sensor data appear in home assistant with out any user interaction .

**Pull request merged**
