### PR TITLE
added a missing letter

### PR DESCRIPTION
**Pull request by adamaze**

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @adamaze, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;companion.home-assistant#155).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by dshokouhi** [comment]
I actually have this change lined up here: https://github.com/home-assistant/companion.home-assistant/pull/154

**Comment by dshokouhi** [comment]
Sorry I didn't merge my PR earlier but just now did.  If you find any more missing characters please feel free to send in another PR!

**Comment by adamaze** [comment]
Ah, I noticed you had a PR out, but didn't take the time to see if you had actually put in the fix I had. I just noticed the name, and went ahead.
Thanks!

**Pull request closed without merging**
