### PR TITLE
Mention opening an entity in command_webview

### PR DESCRIPTION
**Pull request by dshokouhi**
Should also mention the other feature that is supported here :)

### CODE REVIEW

**Comment by dshokouhi** [comment]
closing to reopen as actions look stuck

**Comment by dshokouhi** [comment]
@TomBrien any idea what happened to the checks here? Not sure if we have a command to re-run but closing/re-opening didnt do the trick

**Comment by TomBrien** [comment]
Netlify did this to me the other week, can either ask a GitHub admin to restart checks or just send an empty commit through

**Comment by dshokouhi** [comment]
Closing in favor of another PR to correct some links on the same page

**Pull request closed without merging**
